/* global window */
window.CHAPTERS = [
{
  id: "ch3",
  title: "Chapitres 17–20",
  sentences: [
    "Tu vas à l'école comment ?",
    "Je vais toujours à pied.",
    "Je vais souvent à vélo.",
    "Je vais parfois en bus.",
    "Je ne vais jamais en voiture.",
    "Tu vas à la maison comment ?",
    "Tu vas comment quand il fait beau ?",
    "Tu vas comment quand il pleut ?",
    "Tu vas comment quand il neige ?",
    "Tu vas en train.",
    "Elle va à moto.",
    "Nous allons chez nous.",
    "Vous allez vite.",
    "Elles vont à Namur.",
    "Tu vas rester à la maison.",
    "Il va faire beau.",
    "Elle va chanter.",
    "Nous allons rentrer à vingt heures.",
    "Vous allez commencer la leçon.",
    "Prenez une feuille de format A4.",
    "Pliez votre feuille en deux.",
    "Voici le résultat.",
    "Pliez les ailes.",
    "Comment aller à la rue du Pain ?",
    "Pardon, madame, comment aller à la rue du Pain ?",
    "Ne prenez pas le bus vingt-six.",
    "Il va à la rue de la Saucisse.",
    "Ne prenez pas le tram trente-trois.",
    "Il va à la rue du Chocolat.",
    "Ne prenez pas le métro.",
    "Ne prenez pas le train.",
    "Le métro et le train ne vont pas à la rue du Pain.",
    "Ne prenez pas le bus dix-sept.",
    "Il va à la rue de la Croquette.",
    "Ne prenez pas le tram cent huit.",
    "Il va à la rue de la Grande Frite.",
    "Ne prenez pas le bus vingt-deux.",
    "Il va à la rue du Croque-Monsieur.",
    "Ne prenez pas le tram cent dix.",
    "Il va à la rue du Petit-Suisse.",
    "N'allez pas en voiture.",
    "Allez à pied avec vos bonnes chaussures.",
    "Ou allez à vélo.",
    "Regardez comme il fait beau.",
    "Voici votre maison de vacances.",
    "Entrez, s'il vous plaît.",
    "Ici vous avez le living.",
    "C'est une belle chambre avec une table et six chaises.",
    "Vous avez aussi de bons fauteuils devant la télé.",
    "Dans le coin, vous avez un petit bureau avec une lampe et une radio.",
    "Voici la cuisine.",
    "Elle n'est pas très grande, mais pour les vacances, ça va bien.",
    "Voici la chambre pour les parents avec un grand lit.",
    "Voilà la chambre pour les enfants.",
    "Dans cette chambre, il y a deux lits.",
    "Entre ces deux chambres, vous avez la salle de bains.",
    "Il y a aussi une douche.",
    "Ici vous avez les toilettes.",
    "Il y a aussi un garage pour votre voiture.",
    "Vous avez un grand jardin.",
    "Il y a un joli banc sous ce grand arbre.",
    "C'est une jolie table.",
    "Voici de gentils chiens.",
    "Quand je rentre de l'école, j'ai un copain à la maison.",
    "C'est mon hamster Anatole.",
    "Anatole est son nom.",
    "Je pense toujours à toi.",
    "Mais où est mon hamster ?",
    "Il est toujours bien caché.",
    "Il n'est pas sous la télé.",
    "Il n'est pas dans le fauteuil vert.",
    "Il n'est pas dans le jardin.",
    "Il n'est pas dans le living.",
    "Il n'est pas dans la cuisine.",
    "Il n'est pas dans le bureau.",
    "Est-il dans la salle de bains ?",
    "Est-il caché dans un coin ?",
    "Est-il sous la grande armoire ?",
    "Est-il derrière la porte noire ?",
    "Dans la chambre de ma sœur ?",
    "Dans la douche ?",
    "Dans les toilettes ?",
    "Ou devant l'ordinateur ?",
    "Le voici dans mon lit.",
    "Qu'est-ce que tu aimes faire ?",
    "Qu'est-ce que tu n'aimes pas faire ?",
    "Je n'aime pas faire des exercices.",
    "J'aime faire de la musique.",
    "J'aime chanter.",
    "J'aime faire du sport.",
    "J'aime danser.",
    "J'aime surfer sur Internet.",
    "J'aime regarder la télé.",
    "J'aime écouter la radio.",
    "J'aime jouer au foot.",
    "J'aime jouer au tennis.",
    "J'aime jouer au basket.",
    "Qu'est-ce que tu fais maintenant ?",
    "Maintenant, je fais de la musique.",
    "Tu fais des photos.",
    "Elle fait une jupe.",
    "Nous faisons de la musique.",
    "Vous faites du sport.",
    "Ils font des pulls.",
    "Elles font des tables.",
    "Je vais chez ma copine Annick.",
    "Je vais chez mon copain Victor.",
    "Tu vas chez ton copain Pascal.",
    "Tu vas chez ta copine Margot.",
    "Kim va chez son copain Mehmet.",
    "Elle va chez sa copine Hortense.",
    "Nous allons chez Maxime.",
    "Vous allez chez les sœurs Bonnet.",
    "Vous allez chez les frères Joris.",
    "Ils vont chez Barnabé.",
    "Vous êtes chez nous, mademoiselle.",
    "Mais je ne suis pas Candy.",
    "Vous vous appelez Fanny ?",
    "Vous n'êtes pas Candy ?",
    "Mon père est Marcel Coucou.",
    "C'est une catastrophe.",
    "Elle s'appelle Fanny.",
    "Cette fille est Candy.",
    "Elle a deux yeux et des cheveux.",
    "Mais écoutez.",
    "Je suis une jolie fille.",
    "Vous vous appelez Durieux ?",
    "Vous pouvez monter.",
    "Vous pouvez descendre.",
    "Je vais toujours à pied.",
    "Je ne vais jamais en voiture.",
    "Voici le living.",
    "Voici la cuisine.",
    "Voici une chambre.",
    "Voici un bureau.",
    "Voici la salle de bains.",
    "Voici la douche.",
    "Voici les toilettes.",
    "Voici le garage.",
    "Voici le jardin.",
    "J'aime faire de la musique.",
    "J'aime faire du sport.",
    "J'aime surfer sur Internet.",
    "J'aime faire des devoirs.",
    "Vous vous appelez comment, madame ?",
    "Tu vas en train ?",
    "Vous allez à pied ?",
    "Tu vas rester à la maison.",
    "Elle va chanter.",
    "Nous allons regarder des photos.",
    "Vous allez commencer la leçon.",
    "Je fais mon devoir.",
    "Tu fais des photos ?",
    "Il fait des exercices.",
    "Nous faisons de la musique.",
    "Vous faites du sport.",
    "Bonjour.",
    "Ça va bien, merci.",
    "Moi, je suis Ellen.",
    "Quel est ton nom ?",
    "Moi, je suis Natasha.",
    "Mon nom est Debeer.",
    "Mon prénom est Luc.",
    "Quelle est ton adresse ?",
    "Mon adresse est rue Reinaert numéro trois.",
    "Tu habites une maison ou un appartement ?",
    "J'habite une maison.",
    "J'habite un appartement.",
    "Quel est ton numéro de téléphone ?",
    "À la maison, c'est le 03 480 55 11.",
    "Tu as des frères ou des sœurs ?",
    "Ta sœur s'appelle comment ?",
    "Elle s'appelle Isa.",
    "Ta sœur Isa a quel âge ?",
    "Elle a déjà seize ans.",
    "Mon père s'appelle Joseph.",
    "Ma mère s'appelle Gaby.",
    "Les parents de mon père ont soixante-deux et soixante-six ans.",
    "Vous avez des animaux chez vous ?",
    "Non, nous n'avons pas d'animaux.",
    "Oui, nous avons un chien.",
    "Oui, nous avons deux chats.",
    "Oui, nous avons trois lapins.",
    "Oui, nous avons six oiseaux.",
    "Oui, nous avons dix poissons.",
    "Bonne année.",
    "J'ai un petit cadeau pour toi.",
    "Voici pour ton nouvel an.",
    "Merci beaucoup.",
    "C'est très joli.",
    "Qui est ce garçon ?",
    "Qui est cette fille ?",
    "Qui est ce monsieur ?",
    "Qui est cette dame ?",
    "Qui est ce bébé ?",
    "C'est une copine de ma classe.",
    "C'est le mari de mon prof de français.",
    "C'est la femme de mon prof de néerlandais.",
    "C'est le fils de madame Leroy.",
    "C'est la fille de monsieur Goosse.",
    "Quel est son nom ?",
    "Quel est son prénom ?",
    "Il s'appelle comment ?",
    "Son nom est Duval.",
    "Son prénom est Yves.",
    "Elle s'appelle Roberta.",
    "Il est de Mons.",
    "Elle est de Malines.",
    "Il est Belge.",
    "Elle est Française.",
    "Il a les cheveux blonds.",
    "Il a les yeux bleus.",
    "Il est grand.",
    "Elle est gentille.",
    "Vous cherchez qui, madame ?",
    "Qu'est-ce que vous cherchez, monsieur ?",
    "Le ballon est dans la classe.",
    "Le chat est sous la table.",
    "Le livre est sur le bureau.",
    "Où est le portable ?",
    "Qu'est-ce que tu n'aimes pas faire ?",
    "Tu aimes aller à l'école ?",
    "Tu aimes chanter ?",
    "Tu aimes chatter ?",
    "Tu aimes danser ?",
    "Tu aimes écouter la radio ?",
    "Tu aimes regarder la télé ?",
    "Tu aimes surfer sur Internet ?",
    "Tu aimes jouer au foot ?",
    "Tu aimes jouer au tennis ?",
    "Tu aimes faire de la musique ?",
    "Tu aimes faire du sport ?",
    "Tu aimes faire des devoirs ?",
    "Tu aimes faire des exercices ?",
    "Je vais montrer ma maison.",
    "Entrez, s'il vous plaît.",
    "Il y a un beau banc.",
    "Il y a un bon fauteuil.",
    "Il y a une belle douche.",
    "Il y a une jolie table.",
    "Je porte un T-shirt bleu.",
    "Je porte un pantalon noir.",
    "Je porte des baskets blanches.",
    "J'aime ton pull vert.",
    "Merci, j'aime porter un pull.",
    "Tu aimes porter une veste ?",
    "Oui, j'aime parfois porter une veste.",
    "Tu portes souvent des bottes ?",
    "Oui, je porte parfois des bottes.",
    "Non, je ne porte jamais de bottes.",
    "Tu ne portes jamais de jupe ?",
    "Non, je ne porte jamais de jupe.",
    "Tu vas toujours à pied ?",
    "Tu vas souvent à vélo ?",
    "Tu vas parfois en train ?",
    "Quel est le nom de ton école ?",
    "Quelle est l'adresse ?",
    "Ton école est une grande école ?",
    "Qu'est-ce qu'il y a dans ta classe ?",
    "Il y a un grand tableau.",
    "Il y a douze tables.",
    "Il y a vingt-quatre chaises.",
    "L'école commence à huit heures trente.",
    "L'école finit à midi.",
    "L'après-midi, l'école commence à treize heures trente.",
    "L'école finit à quinze heures cinquante-cinq.",
    "Il est quelle heure ?",
    "La leçon commence quand ?",
    "La fête finit quand ?",
    "Il est sept heures dix.",
    "Il est midi.",
    "Quelle est la date aujourd'hui ?",
    "C'est quand, ton anniversaire ?",
    "Il pleut.",
    "Il neige.",
    "Il va faire quel temps demain ?",
    "Il va faire beau.",
    "Il va faire chaud.",
    "Il va faire mauvais.",
    "Il va faire froid.",
    "Il va pleuvoir.",
    "Il va neiger.",
    "Oui, il va faire beau.",
    "Mais il ne va pas faire chaud.",
    "Non, il ne va pas faire beau."
  ]
},
{
  id: "ch4",
  title: "Phrases supplémentaires",
  sentences: [
    "Bonjour, tu vas à l'école aujourd'hui ?",
    "Je vais à pied avec mon frère.",
    "Ma sœur aime chanter dans la cuisine.",
    "Nous faisons des exercices dans la classe.",
    "Tu cherches ton livre sous la table ?",
    "Il y a un chat dans le jardin.",
    "Regardez cette grande voiture noire.",
    "Mon père porte toujours un pull vert.",
    "J'aime écouter la radio dans ma chambre.",
    "Vous allez en train à Bruxelles ?",
    "Elle fait des photos avec son copain.",
    "Où est le ballon rouge aujourd'hui ?",
    "Le chien dort devant la porte blanche.",
    "Nous avons deux oiseaux et un hamster.",
    "Tu aimes jouer au basket après l'école ?",
    "Il ne porte jamais de chaussures blanches.",
    "Ma grand-mère est très gentille avec nous.",
    "Le professeur parle de la Belgique.",
    "Aujourd'hui, il va faire très beau.",
    "Pourquoi tu restes dans la maison ?",
    "Le petit garçon aime les grands chiens.",
    "Je cherche une gomme dans mon sac.",
    "Vous regardez la télé dans le living ?",
    "Le chat est derrière la grande armoire.",
    "Nous chantons une chanson pour Fanny.",
    "Tu fais du sport avec Victor ?",
    "Elle aime beaucoup son nouveau parapluie.",
    "Attention, le métro va partir maintenant !",
    "Mes copains jouent au foot dans le jardin.",
    "Le bureau est entre les deux fenêtres.",
    "J'ai un cadeau pour ma mère.",
    "Pourquoi les enfants sont-ils dans la cuisine ?",
    "Le hamster mange sous la chaise.",
    "Il fait froid dans cette grande chambre.",
    "Tu peux fermer la fenêtre, s'il te plaît ?",
    "Nous allons regarder des photos ce soir.",
    "Le chien noir aime courir dans le jardin.",
    "Mon frère n'aime pas les exercices difficiles.",
    "Il y a une lampe sur le bureau.",
    "Vous habitez dans une grande maison ?",
    "Je vais parfois en tram avec Charlotte.",
    "Les garçons chantent dans la classe aujourd'hui.",
    "Ma sœur porte une jupe grise.",
    "Le professeur commence la leçon à midi.",
    "Tu as des poissons dans ta chambre ?",
    "Les filles jouent dans le grand jardin.",
    "Le chat blanc dort sur le fauteuil.",
    "J'adore cette chanson française !",
    "Nous avons un nouveau bureau dans la classe.",
    "Tu regardes souvent la télé le soir ?",
    "Mon portable est dans la cuisine.",
    "Elle cherche son frère dans le garage.",
    "Les élèves ouvrent leur livre rapidement.",
    "Il ne fait pas chaud aujourd'hui.",
    "Nous aimons les vacances en France.",
    "Le vélo rouge est devant la maison.",
    "Vous écoutez la radio dans la voiture ?",
    "Le bébé dort dans la chambre des parents.",
    "Pourquoi ton chien est-il sous la table ?",
    "Je porte toujours des baskets noires.",
    "Nous allons chez Marcel cet après-midi.",
    "Tu peux prendre une feuille blanche ?",
    "Le garçon blond aime cette fille.",
    "Il y a des livres sur la table.",
    "Ma mère prépare une belle fête.",
    "Vous aimez cette nouvelle chanson ?",
    "Le professeur ferme la porte maintenant.",
    "Je vais souvent à vélo quand il fait beau.",
    "Le grand arbre est derrière le garage.",
    "Tu fais parfois de la musique ?",
    "Les enfants regardent les oiseaux dans le jardin.",
    "Mon frère cherche ses chaussures noires.",
    "Il y a une douche dans la salle de bains.",
    "Tu peux écouter cette chanson française ?",
    "Le garçon porte un pantalon bleu.",
    "Nous faisons nos devoirs dans le living.",
    "Le petit chat aime dormir sur mon lit.",
    "Pourquoi la fille pleure dans la cuisine ?",
    "Le train arrive dans dix minutes.",
    "Vous aimez les chiens ou les chats ?",
    "Je cherche mon portable partout !",
    "Le professeur parle avec les parents.",
    "Nous allons rentrer à vingt heures.",
    "Tu peux regarder sous le fauteuil ?",
    "La voiture blanche est devant l'école.",
    "Le garçon joue au basket avec Nicolas.",
    "Ma sœur écoute toujours la radio.",
    "Vous faites du sport après les cours ?",
    "Il ne va pas pleuvoir demain.",
    "Les enfants montent dans le bus.",
    "Tu aimes cette belle chanson ?",
    "Le hamster est caché derrière la porte.",
    "Nous regardons un film dans le living.",
    "Le père cherche son fils dans la maison.",
    "Pourquoi les garçons courent-ils dans la classe ?",
    "Je porte un T-shirt noir aujourd'hui.",
    "Le chien dort près de la fenêtre.",
    "Vous pouvez entrer maintenant.",
    "Le professeur distribue les feuilles rapidement.",
    "Tu restes à la maison demain ?",
    "Nous chantons tous ensemble aujourd'hui !",
    "Le ballon est sous la chaise verte.",
    "Ma copine aime les chaussures rouges.",
    "Il y a un grand miroir dans la salle.",
    "Tu peux fermer ton cahier maintenant ?"
  ]
}, 
{
  id: "ch5",
  title: "Phrases supplémentaires 2",
  sentences: [
    "Le professeur regarde les élèves dans la classe.",
    "Tu vas chez ta grand-mère demain ?",
    "Nous aimons beaucoup cette vieille maison.",
    "Le chat gris dort derrière le canapé.",
    "Je cherche mes clés dans la cuisine.",
    "Vous écoutez une chanson française maintenant ?",
    "Le petit garçon joue avec son hamster.",
    "Pourquoi la fenêtre est-elle ouverte ?",
    "Il y a une radio sur le bureau.",
    "Ma sœur porte toujours des bottes noires.",
    "Nous allons en tram à la gare.",
    "Le chien blanc court dans le jardin.",
    "Tu peux écrire ton adresse ici ?",
    "Le père prépare le repas dans la cuisine.",
    "Les filles regardent la télé ensemble.",
    "Je vais souvent au sport avec Victor.",
    "Le parapluie est sous la chaise rouge.",
    "Vous aimez cette table en bois ?",
    "Le garçon roux chante très bien.",
    "Nous faisons des photos dans le parc.",
    "Pourquoi ton frère est-il triste aujourd'hui ?",
    "Le hamster mange derrière le fauteuil.",
    "Je porte un pull gris et noir.",
    "Les enfants jouent devant la maison.",
    "Tu peux fermer la porte blanche ?",
    "Le train part à huit heures vingt.",
    "Nous cherchons notre professeur dans l'école.",
    "Le bébé dort dans un petit lit.",
    "Vous faites parfois du judo ?",
    "Le jardin est très beau au printemps.",
    "Je regarde souvent les oiseaux dehors.",
    "Le garçon aime beaucoup cette chanson.",
    "Pourquoi les élèves parlent-ils si fort ?",
    "Il fait mauvais aujourd'hui à Namur.",
    "Nous avons une nouvelle voiture rouge.",
    "Tu prends le métro ou le tram ?",
    "Le chat noir regarde par la fenêtre.",
    "Ma mère aime les fleurs du jardin.",
    "Vous pouvez ouvrir votre cahier maintenant.",
    "Le chien dort près du grand arbre.",
    "Je vais à vélo avec ma sœur.",
    "Les garçons aiment jouer au tennis.",
    "Pourquoi la lampe est-elle sur le sol ?",
    "Le professeur distribue les livres rapidement.",
    "Nous allons visiter la Belgique cet été.",
    "Tu fais des exercices après le repas ?",
    "Le hamster est dans la salle de bains.",
    "Je ne trouve pas mon portable.",
    "Les enfants chantent une jolie chanson.",
    "Vous aimez les vacances à la montagne ?",
    "Le père lit un livre dans le living.",
    "Pourquoi le chat dort-il ici ?",
    "Il y a des chaises autour de la table.",
    "Nous regardons des photos de famille.",
    "Tu portes souvent des chaussures blanches ?",
    "Le garçon blond aime faire du sport.",
    "La cuisine est entre le garage et le jardin.",
    "Je cherche une feuille pour écrire.",
    "Vous allez rentrer avant midi ?",
    "Le bébé joue avec une balle rouge.",
    "Pourquoi les chiens courent-ils dehors ?",
    "Il neige beaucoup aujourd'hui en Belgique.",
    "Nous aimons écouter la radio ensemble.",
    "Tu peux prendre ton livre maintenant ?",
    "Le professeur parle très vite aujourd'hui.",
    "Les filles dansent dans le living.",
    "Je vais parfois chez mon copain Arthur.",
    "Le parapluie noir est derrière la porte.",
    "Vous regardez souvent des films français ?",
    "Le petit chien aime les enfants.",
    "Pourquoi ton portable est-il sur la table ?",
    "Il y a un beau fauteuil près du bureau.",
    "Nous faisons de la musique après l'école.",
    "Tu veux une gomme ou un crayon ?",
    "Le garçon regarde les poissons dans l'aquarium.",
    "Ma sœur aime beaucoup son nouveau pull.",
    "Vous cherchez la salle de bains ?",
    "Le train arrive bientôt à Bruxelles.",
    "Pourquoi la voiture est-elle dans le jardin ?",
    "Je porte des vêtements très simples aujourd'hui.",
    "Les élèves ferment leur cahier rapidement.",
    "Nous allons manger dans la cuisine.",
    "Tu aimes chanter avec tes copines ?",
    "Le hamster dort sous une couverture.",
    "Le professeur écrit au tableau noir.",
    "Pourquoi les enfants rient-ils si fort ?",
    "Il fait chaud dans cette petite chambre.",
    "Nous avons des poissons rouges et jaunes.",
    "Tu peux regarder derrière la télévision ?",
    "Le chat blanc joue avec une balle.",
    "Vous allez souvent chez vos grands-parents ?",
    "Le garçon aime les jeux sur Internet.",
    "Pourquoi la porte du garage est-elle ouverte ?",
    "Je cherche mes baskets noires partout.",
    "Les filles aiment les chansons françaises.",
    "Nous faisons nos devoirs ensemble ce soir.",
    "Tu prends parfois le bus pour l'école ?",
    "Le père regarde un match à la télé.",
    "Pourquoi ton frère porte-t-il un manteau ?",
    "Il y a un grand lit dans la chambre.",
    "Nous allons écouter la nouvelle chanson.",
    "Tu peux ranger tes affaires maintenant ?",
    "Le chien brun dort devant la cheminée.",
    "Les enfants aiment beaucoup les vacances."
  ]
},
{
  id: "ch6",
  title: "Phrases supplémentaires 3",
  sentences: [
    "Le professeur ouvre la porte de la classe.",
    "Nous commençons la leçon de français maintenant.",
    "Tu vas souvent à l'école en bus ?",
    "Je vais rarement en voiture avec mon père.",
    "Le chat est sous la grande table en bois.",
    "Pourquoi la lumière est-elle allumée ici ?",
    "Nous écoutons une chanson dans la classe.",
    "Le garçon cherche son cahier bleu.",
    "Tu peux m'aider avec cet exercice ?",
    "Il y a une chaise devant le bureau.",
    "Ma sœur fait des photos dans le jardin.",
    "Nous allons chez notre copine ce soir.",
    "Le chien court derrière la voiture rouge.",
    "Tu aimes les exercices difficiles en français ?",
    "Je ne trouve pas mon stylo vert.",
    "Les élèves parlent doucement dans la classe.",
    "Le bébé dort dans la chambre des parents.",
    "Pourquoi ton livre est-il sur le sol ?",
    "Nous regardons un film dans le living.",
    "Le garçon porte un pantalon bleu foncé.",
    "Tu fais souvent du sport après l'école ?",
    "Il y a une lampe sur la petite table.",
    "Ma mère prépare une soupe dans la cuisine.",
    "Nous allons en train à Bruxelles aujourd'hui.",
    "Le chat noir regarde par la fenêtre ouverte.",
    "Tu peux fermer le cahier maintenant ?",
    "Les enfants jouent dans le jardin vert.",
    "Je cherche mes clés dans mon sac.",
    "Le professeur parle très clairement aujourd'hui.",
    "Nous aimons écouter la radio ensemble.",
    "Pourquoi le bus arrive si tard ?",
    "Le garçon blond joue avec son frère.",
    "Tu vas parfois chez ta grand-mère ?",
    "Il y a un grand miroir dans la salle.",
    "Nous faisons des exercices dans la classe.",
    "Le chien dort près de la porte.",
    "Tu peux ouvrir la fenêtre s'il te plaît ?",
    "Je porte un T-shirt blanc aujourd'hui.",
    "Les filles chantent dans la salle de musique.",
    "Nous allons rentrer à la maison bientôt.",
    "Le hamster mange dans sa petite cage.",
    "Pourquoi la table est-elle cassée ?",
    "Tu aimes jouer au tennis avec Victor ?",
    "Il y a une télévision dans le living.",
    "Nous regardons des photos de famille.",
    "Le garçon cherche son portable partout.",
    "Tu peux prendre une feuille pour moi ?",
    "Les enfants courent dans le grand jardin.",
    "Je vais souvent à vélo avec ma sœur.",
    "Le professeur écrit au tableau blanc.",
    "Nous aimons les vacances en Belgique.",
    "Pourquoi les élèves sont-ils en retard ?",
    "Le chat dort sur le fauteuil rouge.",
    "Tu fais des photos avec ton téléphone ?",
    "Il y a un grand bureau dans la chambre.",
    "Nous chantons une chanson très joyeuse.",
    "Le chien court dans la rue calme.",
    "Tu peux m'expliquer cet exercice ?",
    "Je ne vais jamais à l'école en vélo.",
    "Les garçons jouent au foot dans le parc.",
    "Nous allons chez le professeur après l'école.",
    "Le bébé pleure dans la chambre blanche.",
    "Pourquoi ton sac est-il si lourd ?",
    "Tu aimes les chansons françaises modernes ?",
    "Il y a une radio sur la table.",
    "Nous faisons des devoirs ensemble dans le living.",
    "Le chat regarde les oiseaux dehors.",
    "Tu peux fermer la porte maintenant ?",
    "Je porte toujours des baskets blanches.",
    "Les enfants aiment jouer dans la neige.",
    "Nous allons en tram à la gare.",
    "Le professeur donne les livres aux élèves.",
    "Tu fais parfois des exercices difficiles ?",
    "Il y a une lampe dans le coin.",
    "Nous regardons un film français ensemble.",
    "Le garçon joue avec son nouveau ballon.",
    "Tu peux chercher ton cahier bleu ?",
    "Les filles parlent dans le jardin.",
    "Je vais chez mon copain après l'école.",
    "Le chien dort sous la chaise.",
    "Pourquoi la fenêtre est-elle fermée ?",
    "Nous aimons la musique dans la classe.",
    "Tu prends souvent le métro à Bruxelles ?",
    "Il y a un grand tableau noir.",
    "Les élèves ouvrent leurs livres rapidement.",
    "Nous faisons du sport dans le gymnase.",
    "Le chat blanc joue avec une balle.",
    "Tu peux ranger ton sac maintenant ?",
    "Je cherche mon téléphone dans la cuisine.",
    "Les enfants chantent dans le living.",
    "Nous allons visiter notre grand-mère demain.",
    "Le garçon porte un pull vert.",
    "Pourquoi le professeur est-il en colère ?",
    "Tu aimes regarder les oiseaux dans le jardin ?",
    "Il y a une grande table dans la salle.",
    "Nous faisons nos devoirs après le repas.",
    "Le chien court derrière la maison.",
    "Tu peux écouter la radio avec moi ?"
  ]
}
]